/**
 * Shell-integrated blocks (Warp pattern #1).
 *
 * Each shell command becomes a discrete `Block` — its own command line +
 * captured output + exit code + cwd. Implementation strategy: ship a tiny
 * zsh init snippet that emits OSC 1337 markers around every command. The
 * renderer's xterm.js OSC handler intercepts these markers, builds a
 * per-session block array, and exposes it to the agent as cleaner
 * structured context (replacing the regex-strip-ANSI scrollback we use
 * today).
 *
 * For zsh we install our snippet via `ZDOTDIR` — the environment variable
 * that tells zsh where to look for `.zshrc`. Our zshrc sources the user's
 * normal one first, then appends our `preexec`/`precmd` hooks. This is
 * non-invasive: the user's shell config is untouched, and disabling the
 * integration is just a matter of unsetting ZDOTDIR.
 *
 * Critical: when ZDOTDIR is set, zsh ALSO looks in that dir for `.zshenv`
 * and `.zprofile` — and does NOT fall back to `$HOME` for those. So we
 * have to write shim files for them too, each sourcing the user's real
 * one. Without these shims, `~/.zshenv` and `~/.zprofile` are orphaned,
 * which silently breaks anything those files set up (e.g. Homebrew PATH
 * from `eval "$(brew shellenv)"` in `~/.zprofile`).
 *
 * Bash and fish support is deferred to v2 — bash needs a DEBUG-trap
 * workaround and fish has its own event system; both are well-trodden but
 * not required for the macOS default-zsh majority.
 *
 * OSC marker shape:
 *   ESC ] 1337 ; TronBlockStart ; <id> ; <command> BEL
 *   ESC ] 1337 ; TronBlockEnd   ; <id> ; <exit_code> ; <pwd> BEL
 *
 * Both fields after the marker name are URL-encoded so semicolons inside
 * a command don't break the parser.
 */

import * as os from "os";
import * as fs from "fs";
import * as path from "path";

let _initDirCache: string | null = null;

/**
 * Path to a directory containing our `.zshrc` shim. The directory is
 * created (and the zshrc rewritten) on first call; cached thereafter so
 * subsequent PTY spawns don't keep stat'ing the filesystem.
 */
export function getZshIntegrationDir(): string {
  if (_initDirCache) return _initDirCache;

  const dir = path.join(os.homedir(), ".tron", "shell-init");
  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    // Body of the zshrc shim. Note:
    //  - We use `printf` not `echo` for portability across zsh versions.
    //  - Markers go to stdout (which is what xterm parses); they're
    //    OSC sequences so xterm consumes them silently — they never
    //    render as visible text.
    //  - $$ is included in the block id so multiple Tron tabs don't
    //    collide (each PTY has its own zsh process / pid).
    const zshrc = `# Tron shell integration — block markers around every command.
# Generated by Tron; safe to edit but it'll be regenerated on next launch.

# Capture our shim dir before the user's rc runs (it may mutate ZDOTDIR);
# used by the HISTFILE guard below.
__TRON_ZDOTDIR="$ZDOTDIR"

# 1) Source the user's real zshrc first so our hooks layer on top.
# The guard breaks self-recursion when nested Tron sessions chain shims
# (e.g. running a dev Tron inside a Tron terminal).
if [[ -z "$__TRON_SOURCING_ZSHRC" ]]; then
  __TRON_SOURCING_ZSHRC=1
  if [[ -n "$TRON_USER_ZDOTDIR" ]]; then
    TRON_USER_RC="$TRON_USER_ZDOTDIR/.zshrc"
  else
    TRON_USER_RC="$HOME/.zshrc"
  fi
  if [[ -r "$TRON_USER_RC" ]]; then
    source "$TRON_USER_RC"
  fi
  unset __TRON_SOURCING_ZSHRC
fi

# Don't let session history land in Tron's shell-init dir (zsh defaults
# HISTFILE under ZDOTDIR) — keep it in the user's normal history file.
# Compare against the shim dir captured BEFORE the user rc ran: the rc may
# unset or repoint ZDOTDIR, and a live "$ZDOTDIR/"* pattern would then
# clobber deliberately customized HISTFILE locations.
if [[ -n "$__TRON_ZDOTDIR" && ( -z "$HISTFILE" || "$HISTFILE" == "$__TRON_ZDOTDIR/"* ) ]]; then
  HISTFILE="$HOME/.zsh_history"
fi
unset __TRON_ZDOTDIR

# 2) Block markers. We emit OSC 1337 sequences that the Tron renderer
# parses to bracket each command's output. URL-encode command + cwd so
# embedded semicolons don't break the wire format.
__tron_url_encode() {
  local s="$1" out="" c
  # Note: in zsh, \${s:i:1} is parsed as a modifier; we need \${s:$i:1} so the
  # offset is read as an arithmetic value. Same goes for the loop bound.
  for ((i=0; i<\${#s}; i++)); do
    c="\${s:$i:1}"
    case "$c" in
      [a-zA-Z0-9._~-]) out+="$c" ;;
      *) out+="$(printf '%%%02X' "'$c")" ;;
    esac
  done
  printf '%s' "$out"
}

typeset -gi __TRON_BLOCK_ID=0
__tron_preexec() {
  __TRON_BLOCK_ID=$((__TRON_BLOCK_ID + 1))
  printf '\\x1b]1337;TronBlockStart;%s;%d;%s\\x07' "$$" "$__TRON_BLOCK_ID" "$(__tron_url_encode "$1")"
}
__tron_precmd() {
  local exit_code=$?
  if (( __TRON_BLOCK_ID > 0 )); then
    printf '\\x1b]1337;TronBlockEnd;%s;%d;%d;%s\\x07' "$$" "$__TRON_BLOCK_ID" "$exit_code" "$(__tron_url_encode "$PWD")"
  fi
  return $exit_code
}

# 3) Register hooks additively — don't clobber any user-defined ones.
# Idempotent so re-sourcing (or chained Tron shims) can't double-register.
typeset -ga preexec_functions
typeset -ga precmd_functions
if (( \${preexec_functions[(Ie)__tron_preexec]} == 0 )); then
  preexec_functions+=(__tron_preexec)
fi
if (( \${precmd_functions[(Ie)__tron_precmd]} == 0 )); then
  precmd_functions+=(__tron_precmd)
fi

# Reset PROMPT_EOL_MARK so zsh doesn't print a stray % when output
# lacks a trailing newline (already set in env, but belt-and-suspenders).
export PROMPT_EOL_MARK=""
`;

    // Shims for .zshenv and .zprofile. zsh, when ZDOTDIR is set, looks for
    // these files in ZDOTDIR — NOT in $HOME. Without these shims, the
    // user's real ~/.zshenv and ~/.zprofile never run, which breaks
    // anything they set up (Homebrew PATH, version-manager init, etc).
    const sourceUserFile = (filename: string) => {
      const guard = `__TRON_SOURCING_${filename.replace(/[^a-zA-Z]/g, "").toUpperCase()}`;
      return `# Tron shell integration — source the user's real ${filename}.
# Generated by Tron; safe to edit but it'll be regenerated on next launch.
# The guard breaks self-recursion when nested Tron sessions chain shims.
if [[ -z "$${guard}" ]]; then
  ${guard}=1
  if [[ -n "$TRON_USER_ZDOTDIR" ]]; then
    TRON_USER_FILE="$TRON_USER_ZDOTDIR/${filename}"
  else
    TRON_USER_FILE="$HOME/${filename}"
  fi
  if [[ -r "$TRON_USER_FILE" ]]; then
    source "$TRON_USER_FILE"
  fi
  unset TRON_USER_FILE ${guard}
fi
`;
    };

    fs.writeFileSync(path.join(dir, ".zshenv"), sourceUserFile(".zshenv"), "utf-8");
    fs.writeFileSync(path.join(dir, ".zprofile"), sourceUserFile(".zprofile"), "utf-8");
    fs.writeFileSync(path.join(dir, ".zshrc"), zshrc, "utf-8");
    _initDirCache = dir;
    return dir;
  } catch (e) {
    console.warn("[Tron] shell-integration setup failed:", e);
    return "";
  }
}

/**
 * Apply shell-integration env vars to a child-process env. Only sets
 * `ZDOTDIR` for zsh on non-Windows; bash / fish / Windows are left alone.
 * Always preserves the user's previous ZDOTDIR (if any) under
 * `TRON_USER_ZDOTDIR` so our shim can source the correct upstream rc.
 */
/** True when `dir` holds a Tron-generated shim (nested-Tron detection). */
function isTronShellInitDir(dir: string): boolean {
  try {
    const f = path.join(dir, ".zshenv");
    return fs.existsSync(f) && fs.readFileSync(f, "utf-8").includes("Tron shell integration");
  } catch {
    return false;
  }
}

export function applyShellIntegrationEnv(
  env: Record<string, string>,
  shell: string,
): Record<string, string> {
  if (process.platform === "win32") return env;
  // Match `/bin/zsh`, `/usr/local/bin/zsh`, just `zsh`, etc.
  if (!/(^|\/)zsh$/.test(shell)) return env;
  const dir = getZshIntegrationDir();
  if (!dir) return env;
  const out = { ...env };
  // Resolve the ORIGINAL user ZDOTDIR to chain to. An inherited ZDOTDIR that
  // is a Tron shim dir (nested Tron sessions — including this very dir when
  // relaunched from one of our own terminals) must not be chained to
  // directly: the shim would source itself recursively. In that case fall
  // back to whatever original the outer session preserved.
  const userZdot =
    env.ZDOTDIR && env.ZDOTDIR !== dir && !isTronShellInitDir(env.ZDOTDIR)
      ? env.ZDOTDIR
      : env.TRON_USER_ZDOTDIR || "";
  if (userZdot) out.TRON_USER_ZDOTDIR = userZdot;
  else delete out.TRON_USER_ZDOTDIR;
  out.ZDOTDIR = dir;
  out.TRON_SHELL_INTEGRATION = "1";
  return out;
}
